
tasks:
  # Install Java 21 using sdkman
  - init: |
      sdk install java 21
      sdk use java 21
      ./gradlew build

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - richardwillis.vscode-gradle
